### ISSUE TITLE
Wireguard not appearing in results, but installable by ID

### ISSUE THREAD

**Issue by davidjb** [mas-cli/mas#221]
**Describe the bug**
A search for `WireGuard` yields no results but if you go and manually find the ID of the app from the App Store, it's possible to `mas install` it successfully.  Searching for other names works fine (eg `garageband` or `xcode`). 

**To Reproduce**
1. Run `mas search wireguard`
1. See error: `Error: no results found`
1. Open App Store, search for Wireguard.
1. Find the ID of the app (`...` menu --> Copy Link) which is `1451685025`
3. Run `mas install 1451685025`
4. See that installation succeeds:
```shell
==> Downloading WireGuard
==> Installed WireGuard
```

**Expected behavior**
Search results should show WireGuard.

**Actual behavior**
WireGuard is not listed in search results.

**Desktop (please complete the following information):**
 - mas version `1.6.2` (but affects at least `1.5.0` onwards)
 - macOS version: `10.14.3`
 - How did you install mas? `brew install mas`

**Comment by phatblat** [comment]
Thanks for the detailed bug report! I am able to reproduce these results. This is similar to #106 in that the app doesn't show in the `search` results, but can still be installed by ID.

## Background

The `search`, `info` and `lucky` commands use the [iTunes Search API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/#lookup) for looking up apps by name and finding their details. As I've found over the years researching issues like this, these results don't match what you can find in the app store exactly, but they are very close.

## Solutions

For macOS installers which Apple is probably intentionally hiding older ones (#106), I'm building a fixed list into an upcoming release so that these won't be dependent on the iTunes Search API. This makes sense because there is only one new major release of macOS per year.

Now for apps, there are too many of them to find all these exceptions and keep them updated. For now, please log issues like this one whenever you find an app that doesn't show up in search.

Hopefully, I can find the native API that the App Store uses and switch to using that instead of the iTunes Search API because (in theory) this should yield the exact same results as searching the in the App Store GUI app. This is easier said than done because these APIs are private Apple APIs not documented and requires a bit of hackery to find and keep working.

**Comment by maelcum** [comment]
> For now, please log issues like this one whenever you find an app that doesn't show up in search.
Outbank - ID 1094255754

**Comment by zntfdr** [comment]
Hi! I would like to mention that the [Jira App](https://apps.apple.com/app/jira-cloud-by-atlassian/id1475897096) has the same issue (id: 1475897096).

**Comment by phatblat** [comment]
This is fixed now in mas 1.6.4

```
↪ mas search wireguard
  1451685025  WireGuard (1.0.8)
  1475387142  Tailscale (0.98.12)
```

@zntfdr Jira is searchable now too 😄

```
↪ mas search jira
  1475897096  Jira Cloud by Atlassian                      (104.1.0)
```

**Comment by zntfdr** [comment]
Awesome, thanks for the fix! 😃

**Comment by maelcum** [comment]
THANK YOU!!!

**Comment by chapati23** [comment]
adding one more to the list: Outbank, id: 1094255754

**Comment by maelcum** [comment]
> adding one more to the list: Outbank, id: 1094255754

thanks. it had already been added on 20th Aug. 2019 (5th post above yours), though. too bad this still isn't working.
