### ISSUE TITLE
Force re-scan for updates

### ISSUE THREAD

**Issue by eloyaldea** [mas-cli/mas#282]
**Is your feature request related to a problem? Please describe.**
I'm confused because the App Store tells me about a new app version, but 'mas' doesn't, even after doing 'mas upgrade' and 'mas outdated'. It's constantly happening to me so I have to open the Mac App Store and update via itself, so that makes me think that mas isn't as useful as I'd like. So an option to force a scan for updates / oudated apps would be nice.
I'm running the latest 'mas' version 1.7 and running the latest macOS catalina 10.15.5 stable, constantly running 'brew update/upgrade' to keep everything fresh but still 'mas' doesn't upgrade the Mac App Store apps.

**Describe the solution you'd like**
For example same as other brew commands have a -force or --force flag when doing 'mas outdated' or 'mas upgrade'

**Comment by andrewcrook** [comment]
My experience is that mas doesn’t seem to work on Catalina very well or if at all. I think this is caused by the App Store because the App Store app updates also don't show up immediately (as I found out by using MacUpdater) and there doesn’t seem to be a way to force it to check for app updates either. Even by enabling App updates with System Software Updates and using the force option with the macOS builtin command line tool softwareupdate.

**Comment by Stanzilla** [comment]
Same for BigSur

**Comment by phatblat** [comment]
Should be fixed now in [1.8.1](https://github.com/mas-cli/mas/releases/tag/v1.8.1). @eloyaldea can you confirm?

**Comment by eloyaldea** [comment]
I installed 1.8.1. First I checked the App Store for new updates, there was one. I go to `mas outdated`  and it recognizes the new version, `mas upgrade` tells me it's updating said app like so:

> mas outdated
1228738830 NetWorker Lite (5.0.6 -> 5.0.7)

> mas upgrade
Upgrading 1 outdated application:
NetWorker Lite (5.0.6)
==> Downloading NetWorker Lite
==> Installed NetWorker Lite

Running again `mas outdated` shows nothing new, as it thinks it's been upgraded; but the App Store still shows the update there :(. Trying `mas upgrade` again shows this message:

> mas upgrade
2021-03-17 10:09:45.633 mas[12465:518849] INFO: fetch-response is unable to open the file /Users/XXX/Library/Caches/com.mphys.mas-cli/fsCachedData/B472E954-8269-4B7C-8B56-AC1872F6B27A. Errno: 2
Warning: Nothing found to upgrade

Note: I have replaced my user with XXX.

I needed to manually updated from the App Store to get rid of the update showing up.
I hope this response was helpful, I'm happy to keep contributing :).

**Comment by chris-araman** [comment]
The `fetch-response` issue has been addressed with #345 and is expected to be included in the next release. #345 _may_ have also addressed the inconsistency between the App Store app and `mas outdated`.

@eloyaldea, when you press Cmd+R in the App Store app (or select "Reload Page" from the Store menu) in this scenario does it still show the available update?

**Comment by eloyaldea** [comment]
Should I try again what I did or wait until the next release?

**Comment by chris-araman** [comment]
I think the issues reported in this thread should be addressed by #345 and #346.

Please try again after 1.8.2 or later is released.

**Comment by eloyaldea** [comment]
Hi, I don't know if I can still report this bug here as this issue has been closed, but I'm experiencing the same behaviour after 1.8.2: `mas outdated` shows an update, `mas upgrade` upgrades said app, running `mas outdated` again shows nothing to upgrade, but the App Store still shows the update there.

**Comment by chris-araman** [comment]
@eloyaldea, is it possible that a copy of the app is in a location other than `/Applications/`? Perhaps in a system backup or a mounted drive from another macOS partition?

**Comment by eloyaldea** [comment]
Not that I'm aware of, all my apps are installed like usual from the App Store and installed in `/Applications/`, I do have system backups in an external Time Machine drive and in my system's drive there is only one macOS drive with one partition in it.

**Comment by chris-araman** [comment]
I wonder if you might be running into something along the lines of #250 or #309. I'm working on #376, which should address this.

With 1.8.2, does `mas list` show multiple entries for the app(s) that `mas outdated` reports need an update?

**Comment by eloyaldea** [comment]
I assume `mas` behaves correctly when the app is trying to download is not in use. The beginning of this issue comes from the app `NetWorker Lite` with ID `1228738830 ` which is always running in the menu bar at the top, and the App Store comes with a pop-up to close the app before updating and then `mas` fails. I don't know if this can be fixed in `mas` or we need to close all apps before updating manually, but I hope this thread was useful!

**Comment by chris-araman** [comment]
Got it! That's an important distinction. I'm not yet sure how we can address this in `mas`, but I'll reopen this issue for tracking.

**Comment by eloyaldea** [comment]
I thought I was explaining myself clearly sorry 😅🤓 the problem came from the app being opened and `mas upgrade` failing when that happenes. The new title I think it fits better yes, a way for `mas` to detect if an app is opened before attempting the installation and failing to do so. Happy to help!
