### ISSUE TITLE
`outdated` lists latest iOS version instead of macOS version

### ISSUE THREAD

**Issue by gmerlino** [mas-cli/mas#491]
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 13.3.1 (22E261)

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

iOS app versions (mistakenly) being included (and compared) when checking outdated (Mac) apps

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected Behavior

`mas outdated` should not produce as output:

`967805235 Paste (3.1.9 -> 3.2)`

considering there exists no 3.2 version (yet) of the Paste app on the (Mac) App Store.

## Actual Behavior

At each invocation of

`mas upgrade`

Paste (version 3.1.9) will be (re)installed.
By checking with:

`mas outdated`

I get the following output (before, and as well after, invoking upgrade):

`967805235 Paste (3.1.9 -> 3.2)`

so I may guess this (unexpected) output to point right at the root cause.

In particular, there is no 3.2 release (yet), as I guess MAS is (mistakenly) checking the versions of the iOS flavour of the same App, as the iOS latest version of the app in the store indeed is at 3.2, and conflating/comparing the versions both from the Mac side and the iOS side. In this case, iOS version (3.2) would be the latest, compared to Mac version (3.1.9) and naturally take precedence, hence being listed among "outdated" apps.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```bash
$ mas command
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

**Comment by timweston** [comment]
I'm having the same problem with mas. mas outdated shows new versions available, but the new versions are actually the latest iOS app version. Then, as a result, mas upgrade continually tries to upgrade the apps to the new versions.

mas outdated:
<img width="332" alt="mas outdated" src="https://github.com/mas-cli/mas/assets/4657234/2103c0b9-246e-487c-b628-c1d00d9a7af7">

CardPointers in Mac App Store:
<img width="450" alt="CardPointers for Mac" src="https://github.com/mas-cli/mas/assets/4657234/4030cb08-974d-4f53-b721-41d43965150f">

CardPointers in iOS App Store (the "new" version that mas says is available)
![CardPointers for iOS](https://github.com/mas-cli/mas/assets/4657234/359b94ba-de84-4fb8-9bfe-04440a6b5cce)

1Blocker in Mac App Store:
<img width="450" alt="1Blocker for Mac" src="https://github.com/mas-cli/mas/assets/4657234/9041086b-a775-464f-8dd1-b13e986303d3">

1Blocker in iOS App Store (the "new" version that mas says is available)
![1Blocker for iOS](https://github.com/mas-cli/mas/assets/4657234/24b72ffc-4fd9-48ca-98a7-ba2742d70d6a)

**Comment by oschrenk** [comment]
Same for 

```
1115567069 Health Auto Export (2.1.4 -> 7.0.9)
905953485 NordVPN (8.8.3 -> 8.13.0)
1423210932 Flow (2.13.0 -> 3.1.1)
```

**Comment by phatblat** [comment]
I've published a build with a potential fix (#505) for this on the releases page:
https://github.com/mas-cli/mas/releases/tag/v1.8.7-beta.1

Could I get some volunteers to install the `.pkg` attached to that release to see if this resolves any of these issues?

**Comment by gmerlino** [comment]
The beta solves the issue (https://github.com/mas-cli/mas/issues/491) for all packages but one: the only holdout now is Testflight.

**Comment by gmerlino** [comment]
> @gmerlino Can you share your `mas outdated` output? I want to investigate the specific versions of Testflight in the iTunes API.

899247664 TestFlight (3.3.0 -> 3.4.3)

**Comment by Suhaybu** [comment]
Tried using mas 1.8.7-beta.1 but the issue still persists.

## Log:
```
suhayb@iPhone-179 ~ % mas version
1.8.7-beta.1
suhayb@iPhone-179 ~ % mas outdated
1423210932 Flow (2.13.2 -> 3.2.5)
suhayb@iPhone-179 ~ % mas upgrade
Upgrading 1 outdated application:
Flow (2.13.2) -> (3.2.5)
==> Downloading Flow - Focus & Pomodoro Timer
==> Installed Flow - Focus & Pomodoro Timer
suhayb@iPhone-179 ~ % mas outdated
1423210932 Flow (2.13.2 -> 3.2.5)
```
